title: Î¨
url: "https://galaxybra.in"
baseurl: ""

safe: true
markdown: kramdown

collections:
  sides:
    output: true
    permalink: /:slug
  redirects:
    output: true
    permalink: /:slug
  funny_pics:
    output: true
    permalink: /:slug
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _redirects
    values:
      layout: redirect
  - scope:
      path: _sides
    values:
      layout: side

include:
  - .well-known
