title: Î¨
url: "https://galaxybra.in"
baseurl: ""

safe: true
markdown: kramdown

collections:
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: _posts
    values:
      layout: post

include:
  - .well-known
