name: Jekyll Build

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: gem install bundler
        run: gem install bundler
      - name: bundle install
        run: bundle install
      - name: jekyll build
        run: bundle exec jekyll build
      - name: Deploy
        env:
          GITHUB_TOKEN:      ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR:      ${{ secrets.GITHUB_ACTOR }}
        run: |
          set -e
          cd _site
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" && \
          remote_branch="gh-pages" && \
          git init && \
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          echo -n 'Files to commit:' && ls -l | wc -l && \
          git commit -m 'action build' 2>&1 && \
          git push --force $remote_repo master:$remote_branch 2>&1
